"""empty message

Revision ID: 083fffc4764a
Revises: 787cc58a8f70
Create Date: 2019-09-05 15:17:28.647767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '083fffc4764a'
down_revision = '787cc58a8f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('towhom', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'towhom')
    # ### end Alembic commands ###
