"""empty message

Revision ID: cb80fe22c9b4
Revises: 083fffc4764a
Create Date: 2019-09-17 19:40:14.470401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb80fe22c9b4'
down_revision = '083fffc4764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('is_assigner', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_assigner')
    # ### end Alembic commands ###
